### ISSUE TITLE
PRIVACIDAD

### ISSUE THREAD

**Issue by TomasCuevas** [ramirezandradesara/bookstore-mern#1]
Ten cuidado, has dejado la cadena de conexión a tu base de datos en el archivo config.js. Intenta ponerlo en un archivo .env he ignorarlo en el archivo .gitignore para que no se suba al repositorio.

![image](https://github.com/user-attachments/assets/8a7edca6-91d0-4c11-bc69-b373c9d4a193)

**Comment by ramirezandradesara** [comment]
Muchas gracias por el comentario. Aunque sea un proyecto para solo aprender una nueva tecnología, es verdad que no hay que dejar de pensar en la información sensible que puede haber como la conexión de la DB.

Fixeado en el commit  be6de1f831c7dfd5db16e97070890c142f9e49ef.
